# Generated by Django 6.0.5 on 2026-05-22 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('id_card', 'ID Card'), ('key_card', 'Key Card'), ('sim_card', 'SIM Card'), ('kit', 'Joining Kit'), ('mouse', 'Mouse'), ('keyboard', 'Keyboard'), ('headset', 'Headset'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('received', 'Received'), ('not_received', 'Not Received'), ('pending', 'Pending'), ('returned', 'Returned'), ('damaged', 'Damaged')], default='not_received', max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='employees.employee')),
            ],
            options={
                'ordering': ['asset_type'],
            },
        ),
    ]
